Repository cta-observatory/dl1-data-handler, pull requests merged in 2025-04, with the labels that each got.

#160 Update python version according to SPEC0 (include 3.13, drop 3.10)
  .github/workflows/python-package-conda.yml
  .github/workflows/release.yml
  environment.yml
  pyproject.toml
Labels: dependencies

#155 Add choice of focal length
  dl1_data_handler/reader.py
Labels: ready for review

#162 upgrade to ctapipe v0.25.0
  .github/workflows/python-package-conda.yml
  README.rst
  environment.yml
  pyproject.toml
Labels: ctapipe, ready for review, dependencies
